# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment3-MON-Home' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assignment3-MON-Home
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod ‘Firebase/Database’

  target 'Assignment3-MON-HomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Assignment3-MON-HomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
